// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenBetsApi.Data;

#nullable disable

namespace OpenBetsApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214202714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenBetsApi.Models.GameDrawResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DividentAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("divident_amn");

                    b.Property<int>("DrawId")
                        .HasColumnType("integer")
                        .HasColumnName("draw_id");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<int?>("SuccessesCount")
                        .HasColumnType("integer")
                        .HasColumnName("successes_cnt");

                    b.Property<decimal?>("TotalPayout")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_payout");

                    b.Property<string>("WinningCategoryDescr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("winning_category_descr");

                    b.Property<int?>("WinningColumnId")
                        .HasColumnType("integer")
                        .HasColumnName("winning_column_id");

                    b.HasKey("Id");

                    b.HasIndex("WinningColumnId");

                    b.HasIndex("GameId", "DrawId")
                        .HasDatabaseName("idx_game_draw_results_game_draw");

                    b.ToTable("game_draw_results");
                });

            modelBuilder.Entity("OpenBetsApi.Models.WinningColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DrawId")
                        .HasColumnType("integer")
                        .HasColumnName("draw_id");

                    b.Property<DateTime>("DrawTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("draw_time");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<int>("J1")
                        .HasColumnType("integer")
                        .HasColumnName("j1");

                    b.Property<int>("N1")
                        .HasColumnType("integer")
                        .HasColumnName("n1");

                    b.Property<int>("N2")
                        .HasColumnType("integer")
                        .HasColumnName("n2");

                    b.Property<int>("N3")
                        .HasColumnType("integer")
                        .HasColumnName("n3");

                    b.Property<int>("N4")
                        .HasColumnType("integer")
                        .HasColumnName("n4");

                    b.Property<int>("N5")
                        .HasColumnType("integer")
                        .HasColumnName("n5");

                    b.Property<string>("WinningColumnDescr")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("winning_column_descr");

                    b.HasKey("Id");

                    b.HasIndex("DrawTime")
                        .HasDatabaseName("idx_winning_columns_draw_time");

                    b.HasIndex("GameId", "DrawId")
                        .HasDatabaseName("idx_winning_columns_game_draw");

                    b.ToTable("winning_columns");
                });

            modelBuilder.Entity("OpenBetsApi.Models.GameDrawResult", b =>
                {
                    b.HasOne("OpenBetsApi.Models.WinningColumn", "WinningColumn")
                        .WithMany("DrawResults")
                        .HasForeignKey("WinningColumnId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WinningColumn");
                });

            modelBuilder.Entity("OpenBetsApi.Models.WinningColumn", b =>
                {
                    b.Navigation("DrawResults");
                });
#pragma warning restore 612, 618
        }
    }
}
